#############################################
# Application Configuration
#############################################

app.url=https://www.demoblaze.com/

#############################################
# Browser Configuration
#############################################

browser=chrome
headless=false
incognito=false

#############################################
# Wait Configuration
#############################################

implicit.wait=10
explicit.wait=20
page.load.timeout=60

#############################################
# Screenshot Configuration
#############################################

screenshot.on.pass=false
screenshot.on.fail=true

#############################################
# Execution Configuration
#############################################

environment=qa

#############################################
# Reporting
#############################################

allure.results.directory=allure-results